// FC Online Team Data
const LEAGUES = [
  { id: 'epl', name: 'EPL', fullName: '잉글랜드 프리미어리그', country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England', color: '#3d195b', badge: '#00FF87' },
  { id: 'laliga', name: '라리가', fullName: '스페인 라리가', country: '🇪🇸 Spain', color: '#EE8707', badge: '#1A1A2E' },
  { id: 'bundesliga', name: '분데스리가', fullName: '독일 분데스리가', country: '🇩🇪 Germany', color: '#D20515', badge: '#FFBD00' },
  { id: 'seriea', name: '세리에A', fullName: '이탈리아 세리에A', country: '🇮🇹 Italy', color: '#1A56A5', badge: '#29B6F6' },
  { id: 'ligue1', name: '리그앙', fullName: '프랑스 리그1', country: '🇫🇷 France', color: '#0A3C78', badge: '#FFCC00' },
  { id: 'primeira', name: '프리메이라', fullName: '포르투갈 프리메이라', country: '🇵🇹 Portugal', color: '#006600', badge: '#FF4444' },
  { id: 'eredivisie', name: '에레디비지에', fullName: '네덜란드 에레디비지에', country: '🇳🇱 Netherlands', color: '#FF6600', badge: '#FFFFFF' },
  { id: 'kLeague', name: 'K리그', fullName: '대한민국 K리그1', country: '🇰🇷 Korea', color: '#1B3A6B', badge: '#FF0000' },
];

const TEAMS = [
  // ─── EPL ───
  { id: 1, name: '맨체스터 시티', engName: 'Manchester City', league: 'epl', primary: '#6CABDD', secondary: '#FFFFFF', emblem: '🔵', tier: 'S' },
  { id: 2, name: '아스널', engName: 'Arsenal', league: 'epl', primary: '#EF0107', secondary: '#FFFFFF', emblem: '🔴', tier: 'S' },
  { id: 3, name: '리버풀', engName: 'Liverpool', league: 'epl', primary: '#C8102E', secondary: '#F6EB61', emblem: '🔴', tier: 'S' },
  { id: 4, name: '첼시', engName: 'Chelsea', league: 'epl', primary: '#034694', secondary: '#FFFFFF', emblem: '🔵', tier: 'A' },
  { id: 5, name: '맨체스터 유나이티드', engName: 'Manchester United', league: 'epl', primary: '#DA020E', secondary: '#FFE500', emblem: '🔴', tier: 'A' },
  { id: 6, name: '토트넘', engName: 'Tottenham Hotspur', league: 'epl', primary: '#132257', secondary: '#FFFFFF', emblem: '⚪', tier: 'A' },
  { id: 7, name: '뉴캐슬', engName: 'Newcastle United', league: 'epl', primary: '#241F20', secondary: '#FFFFFF', emblem: '⚫', tier: 'B' },
  { id: 8, name: '아스톤 빌라', engName: 'Aston Villa', league: 'epl', primary: '#670E36', secondary: '#95BFE5', emblem: '🟣', tier: 'B' },
  { id: 9, name: '웨스트 햄', engName: 'West Ham United', league: 'epl', primary: '#7A263A', secondary: '#1BB1E7', emblem: '🔵', tier: 'B' },
  { id: 10, name: '브라이튼', engName: 'Brighton', league: 'epl', primary: '#0057B8', secondary: '#FFFFFF', emblem: '🔵', tier: 'B' },
  { id: 11, name: '에버튼', engName: 'Everton', league: 'epl', primary: '#003399', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 12, name: '풀럼', engName: 'Fulham', league: 'epl', primary: '#FFFFFF', secondary: '#000000', emblem: '⚪', tier: 'C' },
  { id: 13, name: '울버햄튼', engName: 'Wolverhampton', league: 'epl', primary: '#FDB913', secondary: '#231F20', emblem: '🟡', tier: 'C' },
  { id: 14, name: '본머스', engName: 'Bournemouth', league: 'epl', primary: '#B50E12', secondary: '#000000', emblem: '🔴', tier: 'C' },
  { id: 15, name: '크리스탈 팔라스', engName: 'Crystal Palace', league: 'epl', primary: '#1B458F', secondary: '#C4122E', emblem: '🔵', tier: 'C' },
  { id: 16, name: '브렌트퍼드', engName: 'Brentford', league: 'epl', primary: '#E30613', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 17, name: '렉섬', engName: 'Wrexham', league: 'epl', primary: '#FF0000', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 18, name: '사우샘프턴', engName: 'Southampton', league: 'epl', primary: '#D71920', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 19, name: '입스위치', engName: 'Ipswich Town', league: 'epl', primary: '#003F8B', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 20, name: '레스터 시티', engName: 'Leicester City', league: 'epl', primary: '#0053A0', secondary: '#FDBE11', emblem: '🔵', tier: 'C' },

  // ─── 라리가 ───
  { id: 21, name: '레알 마드리드', engName: 'Real Madrid', league: 'laliga', primary: '#FEBE10', secondary: '#FFFFFF', emblem: '⚪', tier: 'S' },
  { id: 22, name: 'FC 바르셀로나', engName: 'FC Barcelona', league: 'laliga', primary: '#004D98', secondary: '#A50044', emblem: '🔵', tier: 'S' },
  { id: 23, name: '아틀레티코 마드리드', engName: 'Atlético Madrid', league: 'laliga', primary: '#CE3524', secondary: '#FFFFFF', emblem: '🔴', tier: 'A' },
  { id: 24, name: '세비야', engName: 'Sevilla FC', league: 'laliga', primary: '#D4AF37', secondary: '#FFFFFF', emblem: '⚪', tier: 'B' },
  { id: 25, name: '비야레알', engName: 'Villarreal CF', league: 'laliga', primary: '#FFE135', secondary: '#1A1A1A', emblem: '🟡', tier: 'B' },
  { id: 26, name: '레알 소시에다드', engName: 'Real Sociedad', league: 'laliga', primary: '#004A8B', secondary: '#FFFFFF', emblem: '🔵', tier: 'B' },
  { id: 27, name: '아틀레틱 빌바오', engName: 'Athletic Bilbao', league: 'laliga', primary: '#EE2523', secondary: '#FFFFFF', emblem: '🔴', tier: 'B' },
  { id: 28, name: '베티스', engName: 'Real Betis', league: 'laliga', primary: '#00954C', secondary: '#FFFFFF', emblem: '🟢', tier: 'B' },
  { id: 29, name: '라요 바예카노', engName: 'Rayo Vallecano', league: 'laliga', primary: '#FF0000', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 30, name: '헤타페', engName: 'Getafe CF', league: 'laliga', primary: '#006AB4', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 31, name: '지로나', engName: 'Girona FC', league: 'laliga', primary: '#CD1619', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 32, name: '셀타 비고', engName: 'Celta Vigo', league: 'laliga', primary: '#75AADB', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 33, name: '오사수나', engName: 'CA Osasuna', league: 'laliga', primary: '#C0392B', secondary: '#000000', emblem: '🔴', tier: 'C' },
  { id: 34, name: '발렌시아', engName: 'Valencia CF', league: 'laliga', primary: '#FF7F00', secondary: '#000000', emblem: '🟠', tier: 'C' },
  { id: 35, name: '마요르카', engName: 'RCD Mallorca', league: 'laliga', primary: '#F00000', secondary: '#000000', emblem: '🔴', tier: 'C' },
  { id: 36, name: '에스파뇰', engName: 'RCD Espanyol', league: 'laliga', primary: '#005BA1', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },

  // ─── 분데스리가 ───
  { id: 37, name: '바이에른 뮌헨', engName: 'Bayern München', league: 'bundesliga', primary: '#DC052D', secondary: '#FFFFFF', emblem: '🔴', tier: 'S' },
  { id: 38, name: '보루시아 도르트문트', engName: 'Borussia Dortmund', league: 'bundesliga', primary: '#FDE100', secondary: '#000000', emblem: '🟡', tier: 'S' },
  { id: 39, name: '바이어 레버쿠젠', engName: 'Bayer Leverkusen', league: 'bundesliga', primary: '#E32221', secondary: '#000000', emblem: '🔴', tier: 'A' },
  { id: 40, name: 'RB 라이프치히', engName: 'RB Leipzig', league: 'bundesliga', primary: '#DD0741', secondary: '#FFFFFF', emblem: '🔴', tier: 'A' },
  { id: 41, name: '보루시아 묀헨글라트바흐', engName: 'Borussia M\'gladbach', league: 'bundesliga', primary: '#000000', secondary: '#FFFFFF', emblem: '⚫', tier: 'B' },
  { id: 42, name: '아인트라흐트 프랑크푸르트', engName: 'Eintracht Frankfurt', league: 'bundesliga', primary: '#E1000F', secondary: '#000000', emblem: '🔴', tier: 'B' },
  { id: 43, name: '볼프스부르크', engName: 'VfL Wolfsburg', league: 'bundesliga', primary: '#009A44', secondary: '#FFFFFF', emblem: '🟢', tier: 'B' },
  { id: 44, name: 'FC 우니온 베를린', engName: 'Union Berlin', league: 'bundesliga', primary: '#EB192E', secondary: '#FFFFFF', emblem: '🔴', tier: 'B' },
  { id: 45, name: '베르더 브레멘', engName: 'Werder Bremen', league: 'bundesliga', primary: '#1D9053', secondary: '#FFFFFF', emblem: '🟢', tier: 'B' },
  { id: 46, name: 'FC 샬케 04', engName: 'FC Schalke 04', league: 'bundesliga', primary: '#004D9D', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 47, name: 'FSV 마인츠 05', engName: 'FSV Mainz 05', league: 'bundesliga', primary: '#BE0A14', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 48, name: 'TSG 호펜하임', engName: 'TSG Hoffenheim', league: 'bundesliga', primary: '#1C63B7', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 49, name: 'FC 아우크스부르크', engName: 'FC Augsburg', league: 'bundesliga', primary: '#BA3733', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 50, name: '슈투트가르트', engName: 'VfB Stuttgart', league: 'bundesliga', primary: '#E32219', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 51, name: '함부르크 SV', engName: 'Hamburger SV', league: 'bundesliga', primary: '#0033A0', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },

  // ─── 세리에A ───
  { id: 52, name: '인터 밀란', engName: 'Inter Milan', league: 'seriea', primary: '#010E80', secondary: '#000000', emblem: '🔵', tier: 'S' },
  { id: 53, name: 'AC 밀란', engName: 'AC Milan', league: 'seriea', primary: '#FB090B', secondary: '#000000', emblem: '🔴', tier: 'S' },
  { id: 54, name: '유벤투스', engName: 'Juventus', league: 'seriea', primary: '#000000', secondary: '#FFFFFF', emblem: '⚫', tier: 'S' },
  { id: 55, name: '나폴리', engName: 'SSC Napoli', league: 'seriea', primary: '#087AC1', secondary: '#FFFFFF', emblem: '🔵', tier: 'A' },
  { id: 56, name: '아탈란타', engName: 'Atalanta BC', league: 'seriea', primary: '#1E4494', secondary: '#000000', emblem: '🔵', tier: 'A' },
  { id: 57, name: 'AS 로마', engName: 'AS Roma', league: 'seriea', primary: '#A5192C', secondary: '#F7D41A', emblem: '🔴', tier: 'A' },
  { id: 58, name: '라치오', engName: 'SS Lazio', league: 'seriea', primary: '#87CEEB', secondary: '#FFFFFF', emblem: '🔵', tier: 'B' },
  { id: 59, name: '피오렌티나', engName: 'ACF Fiorentina', league: 'seriea', primary: '#4B0082', secondary: '#FFFFFF', emblem: '🟣', tier: 'B' },
  { id: 60, name: '볼로냐', engName: 'Bologna FC', league: 'seriea', primary: '#B40000', secondary: '#1C4DBF', emblem: '🔴', tier: 'B' },
  { id: 61, name: '토리노', engName: 'Torino FC', league: 'seriea', primary: '#8B0000', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 62, name: '우디네세', engName: 'Udinese Calcio', league: 'seriea', primary: '#000000', secondary: '#FFFFFF', emblem: '⚫', tier: 'C' },
  { id: 63, name: '몬차', engName: 'AC Monza', league: 'seriea', primary: '#FFFFFF', secondary: '#FF0000', emblem: '⚪', tier: 'C' },
  { id: 64, name: '엠폴리', engName: 'Empoli FC', league: 'seriea', primary: '#0E4C96', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 65, name: '제노아', engName: 'Genoa CFC', league: 'seriea', primary: '#AA0000', secondary: '#003EBA', emblem: '🔴', tier: 'C' },
  { id: 66, name: '파르마', engName: 'Parma Calcio', league: 'seriea', primary: '#FBDE00', secondary: '#003087', emblem: '🟡', tier: 'C' },

  // ─── 리그앙 ───
  { id: 67, name: '파리 생제르맹', engName: 'Paris Saint-Germain', league: 'ligue1', primary: '#004170', secondary: '#DA291C', emblem: '🔵', tier: 'S' },
  { id: 68, name: 'AS 모나코', engName: 'AS Monaco', league: 'ligue1', primary: '#E8001C', secondary: '#FFFFFF', emblem: '🔴', tier: 'A' },
  { id: 69, name: 'LOSC 릴', engName: 'LOSC Lille', league: 'ligue1', primary: '#EE1C25', secondary: '#FFFFFF', emblem: '🔴', tier: 'A' },
  { id: 70, name: '올랭피크 마르세유', engName: 'Olympique Marseille', league: 'ligue1', primary: '#2FAEE0', secondary: '#FFFFFF', emblem: '🔵', tier: 'A' },
  { id: 71, name: '올랭피크 리옹', engName: 'Olympique Lyonnais', league: 'ligue1', primary: '#0067B1', secondary: '#FF0000', emblem: '🔵', tier: 'B' },
  { id: 72, name: '스타드 렌', engName: 'Stade Rennais', league: 'ligue1', primary: '#000000', secondary: '#FF0000', emblem: '⚫', tier: 'B' },
  { id: 73, name: '랑스', engName: 'RC Lens', league: 'ligue1', primary: '#E3A519', secondary: '#FF0000', emblem: '🟡', tier: 'B' },
  { id: 74, name: 'OGC 니스', engName: 'OGC Nice', league: 'ligue1', primary: '#000000', secondary: '#FF0000', emblem: '⚫', tier: 'B' },
  { id: 75, name: '스트라스부르', engName: 'RC Strasbourg', league: 'ligue1', primary: '#005BAC', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 76, name: 'FC 낭트', engName: 'FC Nantes', league: 'ligue1', primary: '#FBDE00', secondary: '#008A00', emblem: '🟡', tier: 'C' },
  { id: 77, name: '스타드 브레스트', engName: 'Stade Brestois', league: 'ligue1', primary: '#D40000', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 78, name: '스타드 랭스', engName: 'Stade de Reims', league: 'ligue1', primary: '#FFFFFF', secondary: '#D41111', emblem: '⚪', tier: 'C' },
  { id: 79, name: '앙제', engName: 'Angers SCO', league: 'ligue1', primary: '#000000', secondary: '#FFFFFF', emblem: '⚫', tier: 'C' },
  { id: 80, name: '툴루즈', engName: 'Toulouse FC', league: 'ligue1', primary: '#7C0093', secondary: '#FFFFFF', emblem: '🟣', tier: 'C' },

  // ─── 프리메이라 ───
  { id: 81, name: 'FC 포르투', engName: 'FC Porto', league: 'primeira', primary: '#0046AF', secondary: '#FFFFFF', emblem: '🔵', tier: 'S' },
  { id: 82, name: 'SL 벤피카', engName: 'SL Benfica', league: 'primeira', primary: '#E3001B', secondary: '#FFFFFF', emblem: '🔴', tier: 'S' },
  { id: 83, name: '스포르팅 CP', engName: 'Sporting CP', league: 'primeira', primary: '#008000', secondary: '#FFFFFF', emblem: '🟢', tier: 'A' },
  { id: 84, name: 'SC 브라가', engName: 'SC Braga', league: 'primeira', primary: '#CC0000', secondary: '#FFFFFF', emblem: '🔴', tier: 'B' },
  { id: 85, name: '비토리아 기마랑이스', engName: 'Vitória SC', league: 'primeira', primary: '#000000', secondary: '#FFFFFF', emblem: '⚫', tier: 'C' },
  { id: 86, name: '카사 피아', engName: 'Casa Pia AC', league: 'primeira', primary: '#006400', secondary: '#FFFFFF', emblem: '🟢', tier: 'C' },
  { id: 87, name: '이스트렐라 아마도라', engName: 'Estrela Amadora', league: 'primeira', primary: '#FF0000', secondary: '#000000', emblem: '🔴', tier: 'C' },
  { id: 88, name: '파마캉', engName: 'Famalicão', league: 'primeira', primary: '#FF0000', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },

  // ─── 에레디비지에 ───
  { id: 89, name: '아약스', engName: 'AFC Ajax', league: 'eredivisie', primary: '#D2122E', secondary: '#FFFFFF', emblem: '🔴', tier: 'S' },
  { id: 90, name: 'PSV', engName: 'PSV Eindhoven', league: 'eredivisie', primary: '#E3001E', secondary: '#FFFFFF', emblem: '🔴', tier: 'S' },
  { id: 91, name: '페예노르트', engName: 'Feyenoord', league: 'eredivisie', primary: '#CE0000', secondary: '#000000', emblem: '🔴', tier: 'A' },
  { id: 92, name: 'AZ 알크마르', engName: 'AZ Alkmaar', league: 'eredivisie', primary: '#D2122E', secondary: '#FFFFFF', emblem: '🔴', tier: 'B' },
  { id: 93, name: 'FC 트벤테', engName: 'FC Twente', league: 'eredivisie', primary: '#CC0000', secondary: '#FFFFFF', emblem: '🔴', tier: 'B' },
  { id: 94, name: '위트레흐트', engName: 'FC Utrecht', league: 'eredivisie', primary: '#CC0000', secondary: '#FFFFFF', emblem: '🔴', tier: 'C' },
  { id: 95, name: '흐로닝언', engName: 'FC Groningen', league: 'eredivisie', primary: '#006AA7', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 96, name: 'NEC 네이메헌', engName: 'NEC Nijmegen', league: 'eredivisie', primary: '#006633', secondary: '#FFFFFF', emblem: '🟢', tier: 'C' },

  // ─── K리그 ───
  { id: 97, name: '전북 현대', engName: 'Jeonbuk Hyundai', league: 'kLeague', primary: '#004F9E', secondary: '#FFCC00', emblem: '🔵', tier: 'S' },
  { id: 98, name: '울산 HD', engName: 'Ulsan HD', league: 'kLeague', primary: '#004EA1', secondary: '#FFCC00', emblem: '🔵', tier: 'S' },
  { id: 99, name: 'FC 서울', engName: 'FC Seoul', league: 'kLeague', primary: '#FF0000', secondary: '#000000', emblem: '🔴', tier: 'A' },
  { id: 100, name: '포항 스틸러스', engName: 'Pohang Steelers', league: 'kLeague', primary: '#CC2200', secondary: '#FFFFFF', emblem: '🔴', tier: 'A' },
  { id: 101, name: '제주 유나이티드', engName: 'Jeju United', league: 'kLeague', primary: '#F37022', secondary: '#FFFFFF', emblem: '🟠', tier: 'B' },
  { id: 102, name: '성남 FC', engName: 'Seongnam FC', league: 'kLeague', primary: '#FFD700', secondary: '#1F2B9E', emblem: '🟡', tier: 'B' },
  { id: 103, name: '수원 삼성', engName: 'Suwon Samsung', league: 'kLeague', primary: '#004EA8', secondary: '#FFFFFF', emblem: '🔵', tier: 'B' },
  { id: 104, name: '대구 FC', engName: 'Daegu FC', league: 'kLeague', primary: '#0C3DA2', secondary: '#FFFFFF', emblem: '🔵', tier: 'B' },
  { id: 105, name: '인천 유나이티드', engName: 'Incheon United', league: 'kLeague', primary: '#004EA8', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 106, name: '광주 FC', engName: 'Gwangju FC', league: 'kLeague', primary: '#FFDF00', secondary: '#000000', emblem: '🟡', tier: 'C' },
  { id: 107, name: '강원 FC', engName: 'Gangwon FC', league: 'kLeague', primary: '#005EB8', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
  { id: 108, name: '김천 상무', engName: 'Gimcheon Sangmu', league: 'kLeague', primary: '#004098', secondary: '#FFFFFF', emblem: '🔵', tier: 'C' },
];
